artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
  local_data_file: artifacts/data_ingestion/data.tar.gz
  unzip_dir: artifacts/data_ingestion


prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5



training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5
  test_data: artifacts/data_ingestion/cifar-10-batches-py/test_batch
  train_data: artifacts/data_ingestion/cifar-10-batches-py


evaluation:
  root_dir: artifacts/training
  path_of_model: artifacts/training/model.h5
  training_data: artifacts/data_ingestion/cifar-10-batches-py
  test_data: artifacts/data_ingestion/cifar-10-batches-py/test_batch

prediction:
  path_of_model: artifacts/training/model.h5
  image_name: inputImage.jpg
